### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by condy0919** [Saul-BT/emacs-dots#1]
`Swiper` is bundled with `ivy` and `counsel`. So that you can benefit from `counsel` which provides `counsel-yank-pop` -- a drop in replacement of  `popup-kill-ring`.

**Comment by Saul-BT** [comment]
Oh, thanks for telling me @condy0919  :D, I'll look at it

**Comment by Saul-BT** [comment]
I've added `counsel` and other stuff :) 307398c
Again, thanks for showing it to me
